### ISSUE TITLE
ember-cli torii facebook oauth2 Popup was closed or authorization was denied 

### ISSUE THREAD

**Issue by kkittann** [Vestorly/torii#111]
So I have an application created in ember-cli. Torii is being injected properly on my route, and the Facebook Oauth2 provider launches properly and allows me to log in and receive an authData response.

However it gets a bit odd at that point, if my application is listed under the apps on my Facebook account (not on the developers site but, my personal Facebook as a user would access), launching the authentication using "this.get('torii').open" still triggers the popup, however it closes immediately and reports "Popup was closed or authorization was denied" as opposed to any auth data / any indication that I am signed in. 

The even stranger behaviour is, if I log into my Facebook and delete my app from the app settings and try to log in again, I will occasionally receive an authData response, otherwise it'll give me the usual "Popup was closed or authorization was denied" error. I am a bit new to ember-cli and Torii but I can't seem to pinpoint why I only sometimes receive the authData from Facebook properly and other times I don't. I feel like I might be doing something silly or overlooking something.

**Comment by JoshSmith** [comment]
+1 I anecdotally see this with similar behavior.

**Comment by rduque1** [comment]
@mixonic this also happened for me with LinkedIn. Signed in or signed out it happens.
Like I said in #133 with the timeout on the close of the popup it works.

**Comment by geoffroymontel** [comment]
It also happens with my own provider on Firefox / Mac OS X

**Comment by fsmanuel** [comment]
I have the problem with facebook. google+ works fine. In Chrome it works most of the time. Safari and Firefox have problems. I used the setTimeout @rduque1 mentioned and it helps.

**Comment by netcurate** [comment]
I see similar behavior. For me it's working fine in Chrome but failing in Firefox, every single time. Works fine with Safari.

I haven't tried with Facebook.

**Comment by chrism** [comment]
Just want to add my name to this list, not for Facebook but through Google.

Have been getting intermittent issues using Safari on Mac OS and reports of others having trouble too.

Adding a timeout suggested in #133 fixes it for me

redirect-handler.js
```js
var winPopup = window;
setTimeout(function(){ winPopup.close(); }, 500);
```

Would you consider a PR for this? If so I'd be happy to create one.

Thanks

**Comment by mixonic** [comment]
So perhaps what is happening is that the post message is being cancelled by the window closing. Perhaps these two lines are not running in order:

https://github.com/Vestorly/torii/blob/master/lib/torii/redirect-handler.js#L21-L22

If this is true, what I would like to see is the popup service send a message into the popup, and have that be the trigger for the close. This would be more deterministic than an arbitrary timeout.

**Comment by chrism** [comment]
Understood.

Looking at the https://github.com/Vestorly/torii/blob/master/lib/torii/services/popup.js file I must admit it looks a bit beyond my level of understanding — but i'd like to try to help out so will have a proper look this evening & see if I can work out how to do what you are asking.

**Comment by mixonic** [comment]
@chrism you can find me on freenode as mixonic, in the #emberjs-dev room. I don't think it will be hard to implement the return post-message (or to test), happy to make sure you don't get blocked or waste any time!

**Comment by chrism** [comment]
@mixonic I've forked the repo and used that simple fix for now so i'm not blocked at all, i'd just like to help (if I can). i've taken a good look at the code & have run the tests, so far i've not found a way to make it work but i'm going to keep trying.

thanks for taking the time to offer your help — if i'm still no further forward in the next couple of days then please just let me know a good time for you & i'll jump on irc.

**Comment by r-darwish** [comment]
I'm also experiencing this in Firefox

**Comment by ttdonovan** [comment]
This appears to be an issue in Mac OS X Chrome Canary as well. It does however work in the stable release of Chrome. Is there any new updates on this issue? Anyway I could help or check-in on the current progress.

**Comment by kbullaughey** [comment]
The solution I proposed in this PR (#182) uses a timeout, but it's a timeout in the parent waiting for the message. In the normal flow (i.e., without any errors or failures), the popup will call `postMessage()` and then close itself. The parent will receive `didClose` set the timeout, but as soon as it receives the message, it will close the popup and cancel the timeout and so there's no apparent delay. Only in the case the message is never received will the timeout eventually trigger and reject the promise. 

One question is whether the timeout should be configurable, either making it optional (i.e., wait forever if desired) or a different amount of time. It's currently hard-coded as 5 seconds. In retrospect, this seems very long, and perhaps should be made shorter.
