### ISSUE TITLE
Localization of Facebook Providers

### ISSUE THREAD

**Issue by znake** [Vestorly/torii#146]
Is there a way to localize the Facebook dialogs without having to fork torii? 

Currently the Facebook SDK is just initialized 
for english US $.getScript('//connect.facebook.net/en_US/all.js')
https://github.com/Vestorly/torii/blob/master/lib/torii/providers/facebook-connect.js#L22

But I'd need it to initialize in different languages something like:
  fb_locale = "en_US"
  if portal.locale == "de"
    fb_locale = "de_DE"
  else if portal.locale == "it"
    fb_locale = "it_IT"
  else if portal.locale == "es"
    fb_locale = "es_ES"
  else if portal.locale == "fr"
    fb_locale = "fr_FR"
  else if portal.locale == "nl"
    fb_locale = "nl_NL"
  else if portal.locale == "pl"
    fb_locale = "pl_PL"
  else if portal.locale == "cs"
    fb_locale = "cs_CZ"
  else if portal.locale == "ja"
    fb_locale = "ja_JP"
  else if portal.locale == "pt-br"
    fb_locale = "pt_BR"
  else if portal.locale == "pt-pt"
    fb_locale = "pt_PT"
  else if portal.locale == "ru"
    fb_locale = "ru_RU"
  else if portal.locale == "zh"
    fb_locale = "zh_CN"
  else if portal.locale == "tr"
    fb_locale = "tr_TR"
  js.src = "//connect.facebook.net/"+ fb_locale + "/all.js"

Is something like this possible with torii?

**Comment by mixonic** [comment]
@znake sounds like we could add a configuration option. Totally happy to merge this in, just need a tested implementation. Doesn't seem too tricky!

**Comment by pangratz** [comment]
Looks like this issue can be closed since it been addressed in #168 ...
