### ISSUE TITLE
Torii examples are not runnable

### ISSUE THREAD

**Issue by samdelagarza** [Vestorly/torii#157]
I get a "Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`." error when trying to load the example/basic.html

Steps to repro:

1. git clone torii 
1. npm install
1. grunt server
1. open http://torii-example.com:8000/example/basic.html
-  open dev tools to see the error message
- on yosemite, chrome 41 (not that either of these make a difference)

**Comment by bantic** [comment]
@samdelagarza Yeah, newer ember requires that template compiler for the [runtime compilation](https://github.com/Vestorly/torii/blob/master/example/basic.html#L15-L63) on that page.  pr #158 fixes it. I'll merge it in when the tests go green
