### ISSUE TITLE
Why does torii require the OAuth callback to hit the client?

### ISSUE THREAD

**Issue by JFickel** [Vestorly/torii#159]
This might be a silly question, but why does torii require the auth provider to redirect back to the client? Wouldn't it be one less request if the auth provider redirected to the backend with the temporary code so that the backend could immediately fetch the access token/user data and then redirect the popup to the ember app with the user's information?

**Comment by mixonic** [comment]
The goal is that you can implement all your auth as an API. You only need a redirect on your API or web domain if working with OAuth 1 (Twitter). OAuth2 providers can be implemented purely as APIs. In practice, I find this much simpler than requiring a bunch of redirect logic and some mechanism for passing state to the client outside of the normal API paradigm.

But Torii is very flexible. You could wrap pretty much any behavior.

This is not really an issue, so I'm going to close. Let me know if I've missed anything!
