### ISSUE TITLE
Using `document.location.href` in `config/environment.js` incorrect.

### ISSUE THREAD

**Issue by rwjblue** [Vestorly/torii#161]
The README as the following snippet:

```javascript
/* jshint node: true */
// config/environment.js
module.exports = function(environment) {
  var ENV = {
    /* ... */
    torii: {
      // a 'session' property will be injected on routes and controllers
      sessionServiceName: 'session',
      providers: {
        'facebook-oauth2': {
          apiKey:      'facebook-app-id',
          redirectUri: document.location.href
        }
      }
    }
  };
  return ENV;
};
```

But that file is evaluated in the node context, and `document.location.href` will throw an error.

I'm happy to submit a pull request fixing, but I was unsure what to change it to...

**Comment by ivanvanderbyl** [comment]
I believe `redirectUri: document.location.href` is actually the [default behaviour of the oauth-2 adapter}(https://github.com/Vestorly/torii/blob/master/lib/torii/providers/oauth2-code.js#L87), so removing this _should_ be fine.

**Comment by mixonic** [comment]
Fixed in https://github.com/Vestorly/torii/commit/3ede6737a1ef48847966ba8b3b20ac78c8f42523 thanks @rwjblue  :-)
