### ISSUE TITLE
Oauth2 services don't work with IE11

### ISSUE THREAD

**Issue by rickpern** [Vestorly/torii#169]
Even the demo http://vestorly.github.io/torii/demo.html doesn't work for anything but Facebook connect.  I believe the issue is that postMessage is not working or Ember.$(window).on('message'...) isn't listening correctly.

It's not the popup timeout issue that others have mentioned, it's the fact that the promise is never resolving because the popup isn't sending any message.

**Comment by tehmaestro** [comment]
I get this too in IE11, facebook oauth2. In other browsers it works just fine.

**Comment by joebartels** [comment]
@rickpern @tehmaestro when you repro, does the popup remain open? or does it close but fail?

**Comment by rickpern** [comment]
it closes and fails.  But in my testing i forked torii and removed the window.close() altogether to make sure it wasn't a timing issue.  In IE 10 & IE 11 no message is sent back the opener even when the popup stays open, in all other browsers, the login is completed.  Does that help?

**Comment by tehmaestro** [comment]
In my case, using it on a local project, the popup opens and then closes, but nothing happens. I found out that the promise in `torii.open("facebook-oauth2")` is being rejected. However, `xhr ,status, error` are all `undefined` in the reject callback.

**Comment by joebartels** [comment]
@rickpern we've seen this happen in IE10 and IE11. IE can have a problem sending a regular `postMessage` back to its parent when the popup window does multiple redirects before the final redirect (back to the ember app). And if that's the case, removing `window.close()` may not force `postMessage` to work.  
In your fork, try forcing this condition to be true and see if that helps. This is how we've solved our IE issue. https://github.com/Vestorly/torii/blob/master/lib/torii/services/popup.js#L9

**Comment by tehmaestro** [comment]
I can confirm this works. But my question would be why? As far as I can tell this works in all browsers. Is this a safe modification?

 Thank you for the tip.

**Comment by joebartels** [comment]
@tehmaestro thanks for testing it -especially on windows phone! Haven't seen any side effects from overriding to use the "IE fix" everytime  (although there may be some). 
I've seen the torii master branch not work with IE11 on a coworker's PC, but then work just fine in my virtual machine's IE11(from mac) so it appears to be dependent on the OS and whatever IE updates are installed.
Main take away is that using the "IE fix" all the time appears to increase `postMessage` consistency between windows.
any thought @mixonic ?

**Comment by rickpern** [comment]
@joebartels I believe that change is in the master branch, correct?  That is what I was testing, and it did not work.  I was using a IE 11 on a VM. :(

**Comment by joebartels** [comment]
@rickpern do you mean this change i mentioned?

> In your fork, try forcing this condition to be true and see if that helps. This is how we've solved our IE issue. https://github.com/Vestorly/torii/blob/master/lib/torii/services/popup.js#L9

the master branch is only targeting <= IE10 so you'll have to fork and/or make modification yourself to test it against IE11

**Comment by mixonic** [comment]
@joebartels forcing the fix to always run seems unfortunate, but if you know it fixes something it should probably be PR'd :-p

The ideal is that we find a heuristic that we can use to test for the bug. That said the fix is fairly harmless, and if it works in all other browsers I think making it the default (with a comment explaining the unfortunate behavior it addresses) sounds good :+1:

**Comment by rickpern** [comment]
@joebartels maybe i'm mistaken, but even the link you shared is in the master branch.  I know it's not in the latest release yet, but yes, i've already forked master and attempted to use that fix to no avail.  I'm going to work on it again today. What I'm doing seems standard, i'm not doing any crazy multiple redirects, just the one to authorize on my server.  Everything is on the same domain too.  I'll let you know if I figure anything out.

Thanks guys!

**Comment by joebartels** [comment]
@rickpern I was only trying to highlight the line of code that you could change. e.g.
by changing 
`if (window.attachEvent) {` 
to `if (1===1) {` 
you could test out using the <= IE10 fix in all the browsers, including IE11

**Comment by rickpern** [comment]
@joebartels I tested again in a different VM and your fix is working!!  It must have been the VirtualBox + modern.ie combination that wasn't working.  I tried the master branch using browserstack IE 11 in Windows 7 & 8 and they work.  Sorry about that.  Thanks for all your time and help!!
