### ISSUE TITLE
Config can't load when inside addon and running dummy app

### ISSUE THREAD

**Issue by andyjbas** [Vestorly/torii#170]
I have torii as a dependency of an addon that contains a collection of domain-specific functionality used by many "main" apps. I am running in to issues with the [run time lookup of ENV.torii](https://github.com/Vestorly/torii/blob/7ecf81cd0cc7ccb281162e19daf987531827e240/ember-addon/index.js#L37). Specifically the use of `this.project.name()`. When running tests on the addon, `project.name()` evaluates to the name of the addon and proceeds to try and load config from `addon-name/config/environment` which will be undefined. My assumption is that it should be loading config from `dummy/config/environment` instead, just like it would when attached to a real main app and the `project.name()` lookup resolves properly. Thoughts?

**Comment by iezer** [comment]
Basically we need `this.project.name()` to return `dummy` and not `addon-name` when run within the add-on's test suite. I think we can either change this code to pull the path from `ember-addon.configPath` in `package.json` first and fall back to `this.project.name()`, or we should be able to explicitly set the project name to `dummy` in the test config.

**Comment by mixonic** [comment]
@rwjblue is there a way to access the actual app instead of simply the parent project?

**Comment by joebartels** [comment]
https://www.npmjs.com/package/requiring -a nice module for requiring stuff from the current working directory ![troll](http://www.rw-designer.com/icon-image/7116-16x16x32.png)

**Comment by matthiasleitner** [comment]
using this temporary fix to keep my tests functional for now 

https://github.com/matthiasleitner/torii/commit/db709af42711fc5373a82a91dfabb43397bcb69b

**Comment by mixonic** [comment]
@matthiasleitner that fix seems totally appropriate until we can refactor toward modern addon layout and build steps (torii pre-dates the now-common `addon/` and `app/` layout).

Pushing that fix with a release.

**Comment by mixonic** [comment]
0.3.4 released. Optimistically closing this, but let me know if the fix is incomplete.

**Comment by iezer** [comment]
@mixonic thanks this fixes the issue.
