### ISSUE TITLE
Make session a true Ember.Service

### ISSUE THREAD

**Issue by tim-evans** [Vestorly/torii#171]
I think this is a sensible refactor that would provide more consistency for developers.

**Comment by mixonic** [comment]
@tim-evans There are many things we can improve :-p Torii pre-dates many things we now consider idiomatic, the `addon/` and `app/` addon layout for instance. Making the `torii` and `session` services into `Ember.Service` objects is definitely reasonable.

**Comment by tim-evans** [comment]
Haha, yeah. It's a bit of a mad scramble / constant refactor to keep things feeling svelte.

**Comment by razor-x** [comment]
Just going to reference https://github.com/Vestorly/torii/pull/214 so this can be closed whenever that gets merged in.

**Comment by mixonic** [comment]
@razor-x #214 was already merges. This should already be completed in the latest release. The service is named whatever your configuration names it.
