### ISSUE TITLE
Torii doesn't read configuration from config/environment.js

### ISSUE THREAD

**Issue by deeksy** [Vestorly/torii#173]
Given installation of torii ember-cli-simple-auth and ember-cli-simple-auth-torii, and the setup of some simple actions on a route, login.js, I get an issue when hitting this action on the route:
```
    ...
    googleLogin: function() {
      this.get('session').authenticate('simple-auth-authenticator:torii', 'google-oauth2');
      return;
    }
    ...
```
Issue is:
```Expected configuration value providers.google-oauth2.apiKey to be defined````
  
Relevant part of config/environment.js is:
```
    var ENV = {
     ...
     torii: {
        providers: {
            'google-oauth2': {
            apiKey: 'api-key-here',
            scope: 'profile',
            redirectUri: 'http://localhost:4200'
         },
            'facebook-oauth2': {
             apiKey:      'api-key-here',
             redirectUri: 'http://localhost:4200'
          }
        }
     },
    ...
```
Why is torii not reading the configuration from the environment.js?

**Comment by mixonic** [comment]
@deeksy perhaps this is a regression related to https://github.com/Vestorly/torii/commit/27ae712242e8c8cf987d462701f5c86570d6b486? Can you check version 0.3.3 of Torii?

**Comment by deeksy** [comment]
Hi, apologies for wasting time on this one, but it seems like this was entirely resolved by restarting the 'ember serve' process.
