### ISSUE TITLE
IE8 Issues

### ISSUE THREAD

**Issue by JoshMesser** [Vestorly/torii#178]
I seem to be running into the same problems described in issue #67 reading that over there was a solution put in place a year or so ago. However I'm using Torii 0.3.4 and still seeing this same problem in IE8.

![torii_issues](https://cloud.githubusercontent.com/assets/9802416/7494952/e286f4bc-f3d8-11e4-928b-0e82d8ea05bd.png)

**Comment by JoshMesser** [comment]
I resolved this issue by manually replacing all instances of .catch and .finally with bracket variants. (['catch'] and ['finally']) however this is not an ideal long term solution.

**Comment by mitchlloyd** [comment]
Given that IE 8 is no longer supported by Microsoft or current versions of Ember it seems reasonable to close this issue. @bantic agree?

**Comment by bantic** [comment]
Agreed. If anyone still has ie8-related issues please let us know so we can re-evaluate. 

--
