### ISSUE TITLE
Ember-CLI container.lookup deprecated

### ISSUE THREAD

**Issue by sukima** [Vestorly/torii#186]
Ember-CLI 0.2.5 introduced the following deprecation change:

> DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.

The affected source is in the [initializer line 14](https://github.com/Vestorly/torii/blob/master/lib/torii/initializers/initialize-torii.js#L14).

**Comment by akshayrawat** [comment]
+1

**Comment by JonasFromell** [comment]
+1, would really want to know how we should handle this now, as ember-cli doesn't seem to use the concept of App.Initializer class at all.

**Comment by Padchi** [comment]
Status on this?

**Comment by Ghostavio** [comment]
+1

**Comment by JaroVDH** [comment]
+1

**Comment by michaeldeitcher** [comment]
+1

**Comment by mixonic** [comment]
Fixed in https://github.com/Vestorly/torii/issues/190
