### ISSUE TITLE
Setting popup height

### ISSUE THREAD

**Issue by geoffroymontel** [Vestorly/torii#188]
Is it possible to customize the popup height ?
When asking for some permissions, the default popup is too small and the user has to scroll to log in, and people can't find the button.
![popup1](https://cloud.githubusercontent.com/assets/352910/7959196/536c76fa-09f7-11e5-80c5-37c8226c5d23.png)
![popup2](https://cloud.githubusercontent.com/assets/352910/7959197/536cee3c-09f7-11e5-9f7e-7e5c91b17944.png)

Thanks !

**Comment by whatthewhat** [comment]
Related PR: https://github.com/Vestorly/torii/pull/138

**Comment by geoffroymontel** [comment]
great !! thanks a lot

**Comment by mixonic** [comment]
Closing this in favor of https://github.com/Vestorly/torii/pull/138. Let us make it happen.
