### ISSUE TITLE
Issue where callbacks aren't handled in Chrome and Firefox

### ISSUE THREAD

**Issue by aaronrenner** [Vestorly/torii#193]
I'm running into an issue where the Oauth callbacks aren't being handled by my application. After I sign in over stripe connect, instead of closing the popup window, my application just opens in the popup window.

![screen shot 2015-06-24 at 2 29 45 pm](https://cloud.githubusercontent.com/assets/120878/8341385/c1584d84-1a81-11e5-9120-66d9c38404e3.png)

I am seeing this behavior in Firefox and Chrome on OSX but Safari works correctly. I have tried using torii 0.3.2 and 0.4.1, with ember 1.12.0 and ember 1.13.1, respectively. I have poked around in the Chrome debugger, and it doesn't seem like the window.postMessage code is running. Please let me know what information I can give you to help me figure out what's going on. Thanks in advance for your help.

**Comment by aaronrenner** [comment]
After more debugging, it looks like `window.opener` is null on the popup. I'm researching into why this is happening.

https://github.com/Vestorly/torii/blob/master/lib/torii/redirect-handler.js#L20

**Comment by whatthewhat** [comment]
@aaronrenner I'm seeing the same behaviour with stripe-connect.
The interesting thing is that it was working before and torii was not updated..
Also, google-oauth2 does not have this problem.

Did you have any success with debugging this issue?

**Comment by aaronrenner** [comment]
@whatthewhat I just submitted a pull request (#195) that leverages local storage to communicate between windows instead of `window.opener` and `window.postMessage`. I've tested across the latest Chrome, Firefox, Safari and IE browsers and it appears to be working well. However that code was written this morning, so I wouldn't call it battle tested :smiley:.

**Comment by bagby** [comment]
the exact same thing started happening to me with the **stripe-connect** provider 2 days ago, when this issue was filed. Was previously working in Chrome, still works fine in Safari (we're not testing in Firefox at the moment).

@aaronrenner I'll take a look at your PR, sounds intriguing, and thanks!
