### ISSUE TITLE
Initializers not being called in Ember-cli 

### ISSUE THREAD

**Issue by minasmart** [Vestorly/torii#211]
I figured this out over [here](https://github.com/Vestorly/torii/issues/210), as the cause of a different issue,

In `ember-cli@1.13.X` (and maybe earlier) the code in [lib/torii/load-initializers.js](https://github.com/Vestorly/torii/blob/master/lib/torii/load-initializers.js) isn't being called. This causes some issues where providers really rely on initialization (facebook-connect, etc.)

I'm not sure what's causing this issue, it could be ember-cli, or something in this project, but adding the snippet documented [in the readme](https://github.com/Vestorly/torii/blob/master/README.md#using-torii-via-bower) for apps using bower, instead of the addon `require('torii/load-initializers')['default']();` to my `app.js` forced the initializer to run, and everything works fine.

**Comment by mixonic** [comment]
Ugh, yeah sounds like a bug :-(

**Comment by sheldonnbbaker** [comment]
I've got a similar problem, but adding `require('torii/load-initializers')['default']();` to my `app.js` isn't working - I can see the instanceInitializer is registered in `buildInitializerMethod`, but it's just never called by Ember.

I'm on 2.1.0-beta.2.

**Comment by mixonic** [comment]
@sheldonnbbaker so for 0.6.x I basically rewrote the initializer stuff. I'm certain this issue as originally opened is no longer valid. I walked through testing the codebase on Ember 1.12 - 2.1 version by version, and I may have missed something but I would be surprised.

Can you open a fresh issue? I would need a few more details to attempt a reproduction.

* Are you using Ember-CLI? What version?
* What version of Torii are you using?

**Comment by sheldonnbbaker** [comment]
Using the npm addon is working for me currently - using the bower package caused these issues for me. I'll try and repo it again this weekend.
