### ISSUE TITLE
Replace Ember.keys

### ISSUE THREAD

**Issue by denzo** [Vestorly/torii#215]
DEPRECATION: Ember.keys is deprecated in favor of Object.keys [deprecation id: ember-metal.ember.keys]

**Comment by alisdair** [comment]
Fixed in #202, which has been merged, but there hasn't been a new release yet.

**Comment by mixonic** [comment]
Will have a release shortly. You can try:

```
npm install --save-dev torii@0.6.0-beta.2
```

For now if you want.
