### ISSUE TITLE
Feature Request: Persist Torii session to localStorage

### ISSUE THREAD

**Issue by mwpastore** [Vestorly/torii#219]
Looking for a simple option to read/write the Torii session service data from/to localStorage so that it persists between page reloads and browser restarts. Ideally, something along the lines of: a storage key is specified in the config. The return value of the `open()` method in the adapter is serialized and stored at the key. The default `fetch()` method in the adapter retrieves the session data at the key (if available) and deserializes it. The default `close()` method in the adapter deletes the session data at the key (if present). Changes to the injected session object outside of the adapter update the storage.

**Comment by mixonic** [comment]
@mwpastore that should be trivial to do in an adapter. I don't think we will be adding stock adapters any time soon- though you could publish one in an addon dependent on this one.

**Comment by mwpastore** [comment]
That's fair. You'll have to forgive me, I'm a heckuva newbie. How can I hook onto `this.get('session').set()` to update the in-memory object and re-serialize it to localStorage when changes are made?

**Comment by mixonic** [comment]
Nothing to forgive :-)

`session` does not automatically do anything upon `set`. The behavior is that whatever is returned by `session#open` or `session#fetch` is available on the session. So return `{currentUser: someUser}` and `session.currentUser` is there.

I do not recommend setting things arbitrarily, it would take you out of the lifecycle Torii is trying to encourage.

**Comment by mwpastore** [comment]
Ah, I understand that, but I was under the impression that you could call `session#set` to manipulate its contents outside of the adapter. Thank you for clarifying. 

Regarding "the lifecycle Torii is trying to encourage", could you help me understand what that is? I've read the README a dozen times and something is still not quite clicking for me. Feel free to point me to any online resources or blog posts I might have missed in my googles.

**Comment by mixonic** [comment]
@mwpastore the most important resource would be: http://madhatted.com/2014/6/17/authentication-for-single-page-apps

Torii encourages you to separate authentication of credentials (which I call authorization in that post) and authentication of an application session's current user. This creates flexibility that is advantageous when dealing with the edge cases of auth flows.

**Comment by mwpastore** [comment]
@mixonic Sorry to keep bothering you with this stuff. Just when I think I'm getting there, I get stuck again. Is there a way to tell Torii to refetch/refresh an existing, authenticated session? Trying to manually run `this.get('session').fetch()` results in a predictable ``` `failFetch` for: <StateMachine currentState:'authenticated'>```.

**Comment by mixonic** [comment]
> Is there a way to tell Torii to refetch/refresh an existing, authenticated session?

Those are two different things I presume. You cannot refetch a session, because you would only get what you already have. You can test `session.get('isAuthenticated')` to see if you already have a session. For example [this code](https://github.com/Vestorly/torii/blob/master/lib/torii/routing/authenticated-route-mixin.js#L16) only calls `fetch` if the authentication state is unknown.

You can `session.close()` to destroy a session, then `open` again to refresh.

`fetch` should be a non-interactive version of `open`. Often `fetch` looks to see if there is a cookie or localStorage token, checks to verify that token is good against the API, then resolves. If the token is bad for some reason, `fetch` should likely clear it before rejecting.

**Comment by mwpastore** [comment]
The situation that I've clumsily manufactured myself into is that the session information object has changed on the server side and I need a way to update the corresponding Torii session on the client side. The user is definitely authenticated and definitely has a valid token, I just need Torii to hit the API and fold the response data into the existing session. Reloading the browser tab does the trick, I just need something a little softer.
