### ISSUE TITLE
Multiple adapters with parent class, can't find fetch and close? 

### ISSUE THREAD

**Issue by mwpastore** [Vestorly/torii#221]
I'm attempting to create separate torii-adapters for each of my providers (e.g. facebook-connect, twitter-oauth2), with a parent class containing common functionality. I need some custom logic for each provider when it interfaces with my backend. Torii complains that `fetch()` and `close()` are missing but it seems to find `open()` fine. Not sure if this is a bug or if I'm just doing it wrong, but I could sure use some help!

Here's my attempt at an adapter "base class":

```javascript
// app-name/torii-adapters/common.js
import Ember from 'ember';
import apiAjax from 'app-name/utils/api-ajax';

export default Ember.Object.extend({
  providerName: null,

  init(providerName) {
    this._super();
    this.providerName = providerName;
  },

  open(postData) {
    return apiAjax('POST', `/auth/${this.providerName}/callback`, {
      data: postData
    });
  },

  fetch() {
    return apiAjax('GET', '/session/info');
  },

  close() {
    return apiAjax('POST', '/session/end');
  }
});
```

And my subclass:

```javascript
// app-name/torii-adapters/facebook-connect.js
import CommonAdapter from 'app-name/torii-adapters/common';

export default CommonAdapter.extend({
  init() {
    this._super('facebook');
  },

  open(auth) {
    return this._super({
      provider: this.providerName,
      uid: auth.userId,
      credentials: {
        token: auth.accessToken,
      }
    });
  }
});
```

As I mentioned above, `open()` works fine, but Torii complains with the following error message when I attempt to e.g. logout:

```Error: The Torii adapter must implement `close` for a session to be closed```

Thank you in advance!

**Comment by mixonic** [comment]
Seems like it should work at a glance. If there was an issue, it would likely be at:

* https://github.com/Vestorly/torii/blob/master/lib/torii/services/torii.js#L5

Can you recreate this in a JSBin/Twiddle or repo?

**Comment by mwpastore** [comment]
@mixonic Yes, absolutely. Thank you for responding so quickly. I created a new Ember app with a simple demonstration case and pushed it to a [GitHub repo](https://github.com/mwpastore/vestorly-torii-221) for you to inspect. I probably don't have to tell you this but don't forget to set the `appId` for `facebook-connect` in `config/environment.js` (or you can use my beta one from the penultimate commit if that's easier).  Login, then logout, and the issue will present itself in the console. Renaming `app/torii-adapters/facebook-connect.js` to `application.js` will "fix" the issue. Thanks again!

**Comment by mwpastore** [comment]
Do I need to register my adapter somewhere? i.e. something like:

```javascript
import FacebookConnectAdapter from 'app-name/torii-adapters/facebook-connect';
container.register('torii-adapter:facebook-connect', FacebookConnectAdapter);
```

**Comment by mwpastore** [comment]
I was able to work around this somewhat by renaming `common.js` to `application.js`. Torii finds `session#open()` in `facebook-connect.js` but finds `sesssion#fetch()` and `session#close()` in `application.js`. This at least lets me override the `session#open()` method with provider-specific logic, but it would be nice to someday be able to override the others methods as well.

**Comment by mixonic** [comment]
@mwpastore I believe you're getting mislead by how the `application` default works. It is 100% unrelated to inheritance.

When you call `session.open`, `fetch` or `close` you can optionally pass the name of a torii-adapter. If that adapter exists, it will be used. If not, the `application` adapter will be looked for. See:

https://github.com/Vestorly/torii/blob/master/lib/torii/services/torii-session.js#L7

By having your Facebook adapter extend from common adapter ([code](https://github.com/mwpastore/vestorly-torii-221/blob/master/app/torii-adapters/facebook-connect.js#L3)), you're using the common adapter's methods unless overridden. But keep in mind the facebook-connect adapter will only use when when you call the method with that adapter, ala `session.fetch('facebook-connect')`.

Closing this for now as I don't believe there is a bug here, but let me know if you still have questions.

**Comment by mwpastore** [comment]
@mixonic Ahh, just had the "Oh, duh" moment reading your post. Thank you for the explanation and your patience. Now on to my next source of confusion!
