### ISSUE TITLE
Allow session#fetch to fail gracefully

### ISSUE THREAD

**Issue by mwpastore** [Vestorly/torii#222]
I am using cookies to store my session identifier and checking to see if the cookies are valid in my application route by calling `session#fetch` in the `beforeModel()`. If the session is unauthenticated, and the fetch fails with a specific HTTP status (let's say 403, for example), I want it to simply stay unauthenticated. However, I'm getting the following error message in the console: 

```
GET http://localhost:4200/api/session/info 403 (Forbidden)
Error: Unknown Event: `failFetch` for: <StateMachine currentState:'unauthenticated' >
    at Object.StateMachine.unhandledEvent (state-machine.js:240)
    at Object.StateMachine.send (state-machine.js:203)
    at torii-session.js:77
    at tryCatch (ember.debug.js:56957)
    at invokeCallback (ember.debug.js:56972)
    at publish (ember.debug.js:56940)
    at publishRejection (ember.debug.js:56874)
    at ember.debug.js:33379
    at Queue.invoke (ember.debug.js:910)
    at Object.Queue.flush (ember.debug.js:974)
```

This accomplishes my goal (the session stays unauthenticated) but it's not the prettiest error message. Is there a graceful way to let `session#fetch` fail? I tried trapping it with variations of the following but it still bubbles up to the console log:

```javascript
// app-name/torii-adapters/application.js
export default Ember.Object.extend({
  open() { /* ... */ },

  fetch() {
    return apiAjax('GET', '/api/session/info').catch(response => {
      if (response.jqXHR.status === 403)
        return null;
    });
  },

  close() { /* ... */ }
});
```

(`apiAjax()` is a simple utility function that calls [ic-ajax](https://github.com/instructure/ic-ajax), which is an "Ember-friendly jQuery.ajax wrapper." It accomplishes the same thing as wrapping `Ember.$.ajax` in a `new Ember.RSVP.Promise` as demonstrated in the README.)

Any information about handling errors in a Torii adapter would be extremely helpful.

Thank you in advance.

**Comment by mwpastore** [comment]
This appears to be a regression in the latest commits that enable the `authenticatedRoute` DSL. In addition to the behavior described above, a successful `session#fetch` doesn't initialize the session.  Reverting to the 0.5.1 release restores the correct behavior of `session#fetch` on success and lets me catch and handle a `session#fetch` on failure.

**Comment by mixonic** [comment]
@taras may be worth some investigation if you can make the time.

**Comment by taras** [comment]
Ok, I'll take a look

**Comment by mixonic** [comment]
@mwpastore does https://github.com/Vestorly/torii/pull/224 address your issue? Available in 0.6.0-beta.4

**Comment by mwpastore** [comment]
@mixonic Yes, this appears to be resolved! Thank you.

**Comment by mwpastore** [comment]
@mixonic Wait, I might have to walk that back a bit. As soon as I add back in the `authenticatedRoute()` in `app/router.js` I start seeing this error again. Maybe I'm using it wrong; I'll double-check the documentation.

**Comment by keanedawg** [comment]
This is old but I just want to comment. I was having this same console error and was really confused. Turned out I was accidentally calling my "logout" function when I was already logged out.
