### ISSUE TITLE
"application.has is not a function" booting up 0.6.0-beta.5 

### ISSUE THREAD

**Issue by mwpastore** [Vestorly/torii#233]
Having trouble booting up Torii 0.6.0-beta.5 on Ember 1.13.10. App won't boot with an `application.has is not a function` TypeError in `torii.js` on line 26. Looks like the error maps to line 37 of `lib/torii/bootstrap/torii.js`.

**Comment by duizendnegen** [comment]
also present in 2.0.2

**Comment by bmeyers22** [comment]
+1

**Comment by marcoow** [comment]
also see #225; this is occuring in the ESA tests for 2.0.1, 2.0.0, 1.12.1, #beta and #canary

**Comment by bmeyers22** [comment]
Made a pull request that should fix this, #234

**Comment by mixonic** [comment]
Please check 0.6.0-beta.7 :-) Thank you!

**Comment by mixonic** [comment]
Fwiw getting beta.7 checked out is the last hurdle for a 0.6.0 release :grin:

**Comment by marcoow** [comment]
Ember Simple Auth build is green again: https://travis-ci.org/simplabs/ember-simple-auth

👍

**Comment by mwpastore** [comment]
`sessionServiceName` works great with the `authenticatedRoute` DSL and this error no longer appears on bootup! Thank you all! :+1:
