### ISSUE TITLE
both Facebook options give error in basic example

### ISSUE THREAD

**Issue by kellyselden** [Vestorly/torii#246]
Trying out the example at http://torii-example.com:8000/example/basic.html.
Both Facebook options give the message:
```
App Not Set Up: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
```

**Comment by bantic** [comment]
@kellyselden Can you give some more context? Is that message printed to the console/page as an authentication error? Or does that appear when you attempt to use the user's access token to retrieve data? Fwiw I just flipped the facebook app status to 'public' so hopefully that simply fixes the issue altogether.

**Comment by kellyselden** [comment]
It was in the Facebook styled popup, but your change now fixed it. Thanks.
