### ISSUE TITLE
Uncaught TypeError: container.injection is not a function

### ISSUE THREAD

**Issue by IsaiahJTurner** [Vestorly/torii#248]
Using Ember 2.1.0 I see this <img width="751" alt="screen shot 2015-10-28 at 3 44 55 pm" src="https://cloud.githubusercontent.com/assets/3732588/10800897/ed29784a-7d8a-11e5-9877-56dad7eda20b.png">

**Comment by IsaiahJTurner** [comment]
http://emberjs.com/blog/2015/10/04/ember-2-1-released.html
In 2.1, Ember.Application instances are passed as the first argument to initializer hooks. initializer hooks are where dependencies between object types can be configured, and factories can be registered. Several public APIs will exist on Ember.Application instances, some of them new:

register - register a factory
inject - inject a factory into another factory, or all factories of a type
unregister - remove a factory from registration
resolveRegistration - fetch a registered factory
hasRegistration - check for a registered factory
registerOption, registeredOption, registerOptions, registeredOptions, registerOptionsForType, registeredOptionsForType which manage options for a factory (is it a singleton, can it be instantiated).

Maybe this has something to do with it?

**Comment by Glavin001** [comment]
Have the exact same problem. I really need to upgrade to Ember v2.x and this is a blocker!

**Comment by Glavin001** [comment]
Upgrading from 5.1 to 6.1 resolved this issue for me on Ember v2.2.

**Comment by mixonic** [comment]
Yup, 0.6.0 delivered compatibility with the new 2.1+ APIs. Cheers!
