### ISSUE TITLE
Prevented popup window's CURRENT_REQUEST_KEY should be removed from localStorage

### ISSUE THREAD

**Issue by matthewnessworthy** [Vestorly/torii#249]
In the Torii popup service, if the popup fails to load the `CURRENT_REQUEST_KEY` is not removed for `localStorage`, causing subsequent loads to attempt to close a non-existing window, which in turn causes the browser to issue a warning similar to `Scripts may close only the windows that were opened by it.`.

https://github.com/Vestorly/torii/blob/master/lib/torii/services/popup.js#L84
https://github.com/Vestorly/torii/blob/master/lib/torii/redirect-handler.js#L24

**Comment by keradus** [comment]
Anyone ? is this repo dead ?
