### ISSUE TITLE
Custom provider doesn't receive session data to close method  

### ISSUE THREAD

**Issue by kevintechie** [Vestorly/torii#253]
I have implemented a custom Torii provider (in app/torii-providers/myprovider.js) for use with Ember Simple Auth and have implemented the open, fetch, and close methods.

I have been able to get the open and fetch methods to work properly, but the close method doesn't receive session data as a parameter. The fetch method receives the session data, but close does not. I need the session data that contains an access token in order to remove the token from the server-side access token database.

Is there any way to get the session data when implementing close?

**Comment by kevintechie** [comment]
It turns out that the problem was with Ember Simple Auth not passing the correct info through its Torii wrapper.

**Comment by matthewnessworthy** [comment]
@kevintechie was it something missing your implementation or is it a problem with ember-simple-auth (and if so sould you provide a link to the issue)?

**Comment by kevintechie** [comment]
It is a problem with ember-simple-auth: https://github.com/simplabs/ember-simple-auth/issues/807

**Comment by matthewnessworthy** [comment]
thanks
