### ISSUE TITLE
How to manage redirectUri for multiple envs

### ISSUE THREAD

**Issue by jagthedrummer** [Vestorly/torii#254]
I'm trying to get an ember-cli app to work in several environments, and I'm getting tripped up by the `redirectUri` config for torii. Just relying on torii to set it to the current URL gives us trouble because people can log in from multiple routes within the application and we can't possibly register every possibly route with the provider. Manually setting the entire URI is tricky because of the multiple environments, several of which all run as 'production'. We need to set it to be `window.location.protocol + '//' + window.location.hostname + '/sign-in'`, but the torii config is generated at build time, not run time. Is there are recommended way to handle this?

Relatedly, I think the docs are misleading about how to set `redirectUri`. If you set it to something like `'/my-custom-landing-uri'` as suggested in the docs, then the provider won't be able to redirect back to the app correctly since it's not an absolute url. Maybe we should make it so that torii can recognize when `redirectUri` it not an absolute url and then append the configured uri to the current protocol + hostname combo.

**Comment by mixonic** [comment]
@jagthedrummer we should make this an options to `open` on the provider/session. This would be a good way to off run-time control over the redirectURI

> we can't possibly register every possibly route with the provider

, 
> setting the entire URI is tricky because of the multiple environments, several of which all run as 'production'

It sounds like you'll still need to register a fairly large list of redirect URIs with the provider services themselves- Torii can't work around that, many providers just require you to list all potential redirect URIs.

**Comment by bantic** [comment]
It should be safe to have only one redirectUri: the base url for your ember app. Since Torii opens another window (popup), the redirect happens there and shouldn't be dependent on the route the user happens to be looking at in the ember app in the original window.

So the flow is:
Main Window -> opens popup to OAuth provider url -> user authenticates, consents -> OAuth provider redirects to redirectUri (aka "http://your-app.com/") where Torii detects the OAuth data from query params or hash fragment -> closes popup and resolves promise in main window

Let me know if I am misunderstanding the use case, though.

**Comment by mixonic** [comment]
We use `localStorage` for the message passing, so they do need to be at the same domain. But you are right that you only need one per domain.

**Comment by jagthedrummer** [comment]
@bantic @mixonic We do indeed need to register a few domains with the provider, which is no problem. But we also have to configure the client to know which domain it is deployed at, which seems unnecessary. We're deploying the same code to staging (staging.foo.com) and production (www.foo.com) envs on heroku, both of which have the main `environment` variable set to `'production'`. That means that just relying on the `if (environment === 'production') {...}` block in `config/environment.js` doesn't work. For now we're setting an additional env variable that just contains the root URL for where the app is deployed (either `'http://staging.foo.com'` or `'http://www.foo.com'`). I was just thinking it would be nice if I could set `redirectUri` to be `'/sign-in'`, as suggested by the docs but which is actually insufficient, and have things just work. Am I explaining that ok?

**Comment by jagthedrummer** [comment]
Just to clarify, when `redirectUri` is set as a relative url like `'/sign-in'` the relative url is passed as-is to the provider in the auth call. For instance : `/oauth/authorize?redirect_url=%2Fsign-in&...`

This causes the call to fail because the application has to be registered with the provider as an absolute url and the provider expects the `redirect_uri` param to contain the full absolute url.

I'm proposing that it would be handy for torii to detect if the `redirectUri` config value is a relative url and to prepend that value with the protocol/host combo of the currently running app.

**Comment by jagthedrummer** [comment]
Derp. I see what you're saying about just leaving the redirect uri as the base url. I'm an idiot...

**Comment by bantic** [comment]
@jagthedrummer Does that work!? Sorry for not responding yet to your above-above  comment.

Another option is that I believe you can define a function for `redirectUri` — it will be evaluated at run time rather than build time. I may be mis-remembering, but I'm pretty sure that is there as an escape valve for you if you need more exotic redirect-uri stuff.

**Comment by jagthedrummer** [comment]
This is not an issue, it was just operator error.

**Comment by NullVoxPopuli** [comment]
so how do I configure torii to have additional parameters?
I'm using stripe-connect, and I'm using it to tie to inidividual objects -- and I'd like to be able to pass the object id and type in the redirect URL, so that when stripe redirects back to my app, I know what object the auth data is for.
