### ISSUE TITLE
Provide a mechanism to initialize a provider not through ENV configuration

### ISSUE THREAD

**Issue by vmalloc** [Vestorly/torii#259]
In some cases it could be useful for the client to get the OAuth2 identifier from the server (e.g. when the identifier is stored in a database). Is there a way to initialize a provider with torii in such cases?

**Comment by bantic** [comment]
@vmalloc Torii looks up the provider from the container using `torii-provider:${name}` (see https://github.com/Vestorly/torii/blob/master/addon/services/torii.js#L4), so if your application `register`s the provider at runtime using the key that torii expects, it should be able to find it. thanks!

**Comment by vmalloc** [comment]
@bantic thanks!
