### ISSUE TITLE
Ember Data 2.3.0+ fails to boot with: No application initializer named 'store'

### ISSUE THREAD

**Issue by tstirrat** [Vestorly/torii#261]
As the title says, torii [relies on the `store` initializer](https://github.com/Vestorly/torii/blob/e8b4e7d484544b2fb7bd921abdf15f23a42105b5/lib/torii/initializers/initialize-torii.js#L15-L17) that seems to be gone, or renamed, in Ember Data 2.3.x

**Comment by tstirrat** [comment]
Looks like it might be ["ember-data" now](https://github.com/emberjs/data/blob/v2.3.0/app/instance-initializers/ember-data.js#L4).

**Comment by spovich** [comment]
I'm seeing this also with ember-data 2.3.1 and torii.

**Comment by bmac** [comment]
This is an regression with Ember Data. I've opened an issue to track it here: https://github.com/emberjs/data/issues/4087 and I plan to do another 2.3 patch release after this is fixed.

**Comment by bmac** [comment]
@tstirrat Do you mind trying out Ember Data [v2.3.2](https://github.com/emberjs/data/releases/tag/v2.3.2) with your application to see if it fixes the issue?

**Comment by bantic** [comment]
@tstirrat Thanks for pointing this out. We're likely going to remove the store-injection initializer from Torii altogether in the next release — since the store is exposed as a service it's easy to bring it in to your torii provider or adapter as needed, anyway.
