### ISSUE TITLE
Restore session from chosen adapter?

### ISSUE THREAD

**Issue by balinterdi** [Vestorly/torii#268]
1. Users could authenticate themselves against multiple providers in the same app and I think it's a good idea to have the `open` and `close` methods of the adapters for these providers stored in a file that is named according to the provider (for example under `torii-adapters/google-oauth2-bearer.js`).

2. When it comes to the automatic restoring (fetching) of the session, you need to choose one adapter whose `fetch` method will be called, you cannot restore a session from multiple providers. My issue is that this is [automatically assumed to be the `application`](https://github.com/Vestorly/torii/blob/f47b231594445a26b6247fd1eb0c1a14cc20a4bd/lib%2Ftorii%2Frouting%2Fapplication-route-mixin.js#L16) which forces me to always create an `application` adapter to be able to define its `fetch` method.

If I want to have both 1. and 2. implemented then I need two adapters, one `application`.

This is not really a biggie but I wonder if we might have a configuration option to designate which adapter should restore the session, something like the following:

```javascript
// config/environment.js
torii: {
  sessionServiceName: 'session',
  restoreFrom: 'google-oauth2-bearer',
  (...)
}
```

**Comment by mixonic** [comment]
@balinterdi you can just have `google-oauth2-bearer` inherit from `application`, or re-export. This is pretty standard through the Ember ecosystem and I'd like to keep it.

**Comment by balinterdi** [comment]
I tried the following:

```js
// app/torii-adapters/google-oauth2-bearer.js
import ApplicationAdapter from 'torii/adapters/application';

export default ApplicationAdapter.extend({
  open(authorization){
    (...)
  },

  fetch() {
    (...)
  },

  close() {
    (...)
  }
});
```

But when Torii fetches the session, it still finds the default, empty implementation of ApplicationAdapter which just throws an error. Maybe I have to inherit **and** re-export? If so, do I have to do the re-exporting in an initializer? Thank you.

**Comment by kategengler** [comment]
I was attempting to have an adapter named 'api' recently, matching my provider. It worked with 'open' and 'close' but not with 'fetch'. Once I moved the adapter to be named 'application', it worked; I think this may be a bug.

**Comment by balinterdi** [comment]
@kategengler I think it's simply because Torii uses the `application` adapter to fetch (restore) the session, see [here](https://github.com/Vestorly/torii/blob/master/lib%2Ftorii%2Frouting%2Fapplication-route-mixin.js#L16).

That's also what my point is with this ticket, I'd like to have all methods in place, preferably named "semantically" (in your case: `api`).

If you don't need a configuration option for that, all the better, I just don't know how to make what Matt said above work :)

**Comment by kategengler** [comment]
@balinterdi Thanks, I didn't think about it enough before to realize that its only the auto-restoring of the session provided by the Router DSL that has this problem. Previously I had done: `this.get('service').fetch('api');` but of course the built in method can't know what provider I mean to open, hence your suggestion of a configuration option. 

Re, part 1 of your issue, I think you may have meant "methods of the adapters for these providers stored in a file that is named according to the provider (for example under torii-**adapters**/google-oauth2-bearer.js)."

**Comment by balinterdi** [comment]
Yes, that's what I meant, thank you, I've now fixed it.

**Comment by balinterdi** [comment]
I think I understood (and made to work) what Matt had in mind:

```js
// app/torii-adapters/google-oauth2-bearer.js
export default Ember.Object.extend({
  fetch() {
    (...)
  },

  open(authorization){
    (...)
  },

  close() {
    (...)
  },
});
```

```js
// app/torii-adapters/application.js
import GoogleOAuth2BearerAdapter from './google-oauth2-bearer';

export default GoogleOAuth2BearerAdapter;
```

@mixonic Is this what you meant?

I find this a convenient way as a solution to my problem and is a better than adding a configuration variable, so I'm going to close this issue.
