### ISSUE TITLE
Store no longer available in adapters with Ember Data >=2.3.0

### ISSUE THREAD

**Issue by balinterdi** [Vestorly/torii#270]
Torii injects the `store` onto adapters [on condition that `window.DS` exists](https://github.com/Vestorly/torii/blob/master/lib%2Ftorii%2Fbootstrap%2Ftorii.js#L38).

However, it seems that ED 2.3.0 no longer exposes DS on window, so that initialization does not run, and  `this.get('store')` in adapter code is undefined, leading to bugs.

**Comment by bantic** [comment]
#271 is part of v0.7.0-beta.4, which removes eager injection of store into providers/adapters altogether, so that should fix this.

If your providers/adapters need the store, please use standard `store: Ember.inject.service()` usage in them.

**Comment by balinterdi** [comment]
Yes, that makes sense.
