### ISSUE TITLE
session.isAuthenticated doesn't work properly in components

### ISSUE THREAD

**Issue by TheSavageJohn** [Vestorly/torii#289]
I need to display some navigation menus accordingly `isAuthenticated` value.
For example: 
application.hbs

```
{{#if session.isAuthenticated}}
  User signed // work properly
{{else}}
  User signed out // work properly
{{/if}}
```

But if I create component and add `session` param, something went wrong:
application.hbs
`{{my-menu session=session}}`
my-menu.hbs

```
{{log session.isAuthenticated}}
{{#if session.isAuthenticated}}
  {{link-to 'First link' 'first-route'}}
  {{link-to 'Second link' 'second-route'}}
{{else}}
  {{link-to 'Third link' 'third-route'}}
{{/if}}
```

When I make sign-in/sign-out all of them links are displayed. So, if I signed in, i can see `Third link` until page refresh.
Debug return next values:

```
false // if I wasn't be sign in
undefined
true // after success sign in
```

I tried to send `session`, `session.isAuthenticated`, inject `session` service in component - strange behavior are still reproduced.

ember#2.5.0
torii@0.6.1

**Comment by oskarrough** [comment]
Does the behaviour change if you inject the `session` directly in the component instead of passing it down? Not that it's the solution but I also experienced (async?) issues with this.

**Comment by bantic** [comment]
Since there hasn't been any comments here for a while I'm going to close this for now. @TheSavageJohn please reopen if necessary! Thanks
