### ISSUE TITLE
Issue with private mode in mobile safari

### ISSUE THREAD

**Issue by anthonycollini** [Vestorly/torii#301]
Hello, I'm using Ember Simple Auth, which uses Torii. There's an issue where we can't authenticate the user in private browsing mode in mobile safari. It comes back with a `QuotaExceededError: DomException 22`.

Marco says :

> That seems to be a bug in torii which seems to use localStorage internally - check out the stack trace.

https://github.com/simplabs/ember-simple-auth/issues/1013

Any help in figuring this out would be appreciated.

**Comment by bantic** [comment]
@anthonycollini Thanks for reporting! You're right; in Safari private browsing access to local storage is restricted altogether. This is being tracked in #265.
