### ISSUE TITLE
Torii Session Service does not inject into routes/controllers

### ISSUE THREAD

**Issue by thedig** [Vestorly/torii#312]
Have pored over several tutorials for an EmberFire / Torii setup and am not able to get the `session` service to work at all. Is a step missing or is there possibly an issue with newer versions of EmberJS when injecting the session service?

`environment.js`

```
module.exports = function(environment) {
  var ENV = {
    ...
    firebase: {
      apiKey: '',
      authDomain: '',
      databaseURL: '',
      storageBucket: ''
    },
    torii: { sessionServiceName: 'session' },
    ...
  };
}
```

`app/torii-adapters/application.js`

```
import Ember from 'ember';
import ToriiFirebaseAdapter from 'emberfire/torii-adapters/firebase';

export default ToriiFirebaseAdapter.extend({
  firebase: Ember.inject.service()
});
```

`routes/application.js`

```
import Ember from 'ember';

export default Ember.Route.extend({
  beforeModel: function() {
    return this.get("session").fetch().catch(function() {});
  },
  ...
}
```

Browser console when visiting application route:

```
ember.debug.js:28058Error while processing route: index Cannot read property 'fetch' of undefined TypeError: Cannot read property 'fetch' of undefined
```

Guides consulted while trying to sort this out: 
http://www.programwitherik.com/emberjs_2-0_example_app_with_firebase/
http://www.danielgynn.com/third-party-auth-in-ember-with-firebase/

Package versions - 
    "ember-cli": "2.3.0",
    "emberfire": "2.0.1",
    "ember": "~2.3.1",
    "firebase": "^3.0.0"

**Comment by v3ss0n** [comment]
same problem , i just reported.

It is running fine with `ember serve` but when running on production it give that weird error.

**Comment by mixonic** [comment]
@thedig this seems like a bug. [this file](https://github.com/Vestorly/torii/blob/master/addon/bootstrap/session.js) should be running and setting up the injection [when called here](https://github.com/Vestorly/torii/blob/606334ca1832ecadc75628f8b6a2c4e110c1e642/app/initializers/initialize-torii-session.js#L17).

**Comment by kcgolden** [comment]
I npm install'd torii and it worked after that. Something is wrong with the bower side.

**Comment by andruby** [comment]
I encountered the same problem. @kcgolden I also did an extra `npm install torri` without any luck. How did you managed to get it working?

Package versions:

"ember-cli": "2.9.1",
"ember-data": "^2.9.0",
"emberfire": "2.0.5",
"torii": "0.8.1"

**Comment by andruby** [comment]
Never mind. I had a typo in the environment configuration. I had `sessionsServiceName` instead of `sessionServiceName`.

**Comment by ewaschen** [comment]
Bump, I followed https://www.danielgynn.com/third-party-auth-in-ember-with-firebase/
Error I'm getting is just an undefined.  Trying google sign in with firebase and getting a random undefined.

![embererror](https://cloud.githubusercontent.com/assets/9055167/21469643/bb858e02-ca2b-11e6-820c-fb5d6bdc2738.png)

**Comment by albertvolkman** [comment]
Also getting this issue...

**Comment by albertvolkman** [comment]
Oddly enough, I built a new Ember instance and it now works following this guide-

https://blog.isnorcreative.com/2016/07/30/ember-firebase.html

I had tried using it before, and it wasn't working. After resetting my original env and then copy/pasting everything over, it now works... ¯\_(ツ)_/¯

**Comment by ewaschen** [comment]
For me it was because I hosted my application on cloud9 so it had its own public url.  For Firebase auth, any domain other than localhost or the firebase domain which you can deploy your app must be added to the whitelist in the firebase console.

**Comment by mixonic** [comment]
I'm going to close this as it seems the original issue is ok, and there are a few other issues that ended up mixed in here. Please feel free to open something fresh!
