### ISSUE TITLE
Abandoned project? Alternatives?

### ISSUE THREAD

**Issue by v3ss0n** [Vestorly/torii#316]
Torii fails to work on mobile devices , is there any active forks ?
If this project abandoned , any plan to hand over?

**Comment by mixonic** [comment]
The [network chart](https://github.com/Vestorly/torii/network) is probably best for identifying an active fork. I'd not consider the project abandoned.

By "fails to work on mobile device" I think you mean https://github.com/Vestorly/torii/issues/315, I'm not familiar with OpenFB but I'd be happy to look at an implementation and some more docs.

Happy to give commit bit to contributors and help share the maintenance load! We can do better at that. However I don't expect someone would pick up OpenFB implementation without a need for it themselves.

Thanks!

**Comment by v3ss0n** [comment]
Thanks a lot for the response. 
Right now i am writing a facebook-connect4 provider , for torii , which is cordova's facebook native login plugin. Its close to working now.

Regarding OpenFB it works on both platforms.
