### ISSUE TITLE
How would I go about revoking access?

### ISSUE THREAD

**Issue by gin93r** [Vestorly/torii#318]
I'm using Torii for google signin. The invalidate method signs a user out, but I do not see a way to call the `disconnect()` method to revoke access.

**Comment by bantic** [comment]
@gin93r Thanks for opening this issue.
If you're referring to instructing Google to sign out the user, or revoke the access token that it issued your app for that user, that would be outside Torii's domain. It would be something you'd need to do through Google's API directly, if they provide that functionality (or tell the user to explicitly disconnect your app from their account through Google's interface).
I'm closing for now, but if I misunderstood, or you can share some more information, please feel free to comment and re-open.
