### ISSUE TITLE
Interested in blueprints?

### ISSUE THREAD

**Issue by srvance** [Vestorly/torii#328]
It seems blueprints to generate `torii-adapters` and `torii-providers` could be a useful addition. If you're interested I can do the work and submit a PR.

Adapters would only have one variant. Providers could have multiple variants and be handled similarly to how ember-simple-auth handles authenticators and authorizers with a `--base-class` option.

**Comment by srvance** [comment]
I see there's already a PR #311. Any idea if and when it will be accepted?

**Comment by w-hat** [comment]
I've been wondering that too... :)

**Comment by bantic** [comment]
@w-hat @srvance Thanks for this suggestion. I added a few comments to #311. Would be happy to merge in some blueprints once the comments there are addressed. thanks!
