### ISSUE TITLE
stripe-connect not working in FastBoot

### ISSUE THREAD

**Issue by t4t5** [Vestorly/torii#329]
Running in non-fastboot mode works great, but with it, it seems like the authorizationCode is never returned to the app:

```
The response from the provider is missing these required response params: code, state
```

Anyone know what the reason might be?

**Comment by t4t5** [comment]
Turns out this is actually not the library's fault.

I had a `transitionTo`-redirect for logged in users in my Ember app. The problem is that in FastBoot, this would cause a redirect on the server side, thus clearing all the necessary query parameters (`code` and `state`) before Torii had time to evaluate them.

My solution was to prevent any `transitionTo` if either `code` or `state` is set as a query param.

**Comment by marcowilliam** [comment]
Do you still remember how did you prevent any transitionTo if either code or state is set as a query param?
