### ISSUE TITLE
Popup not working in Edge

### ISSUE THREAD

**Issue by kevinansfield** [Vestorly/torii#335]
Using Edge on Windows 10, torii seems to have problems when using the auth popup.

I'm seeing an instant `remote could not open or was closed` error then the popup opens full screen, it's possible to go through the flow in the new window but Edge will warn about the window being closed and doesn't seem to communicate back to the app.

The only other mention of issues in Edge I can find is a comment on a closed issue here https://github.com/Vestorly/torii/issues/63#issuecomment-278135077

**Comment by z6aak** [comment]
Have the same issue on Edge and IE. Chrome and Firefox have no problems
