### ISSUE TITLE
QueryString.requiredParams is frozen

### ISSUE THREAD

**Issue by marcoow** [Vestorly/torii#337]
We are running into this issue in the Ember Simple Auth dummy app: simplabs/ember-simple-auth#1260 currently and the reason seems to be that the `QueryString`'s `requiredParams` property is frozen. It also seems to relate to this issue in Ember.js itself emberjs/ember.js#15020 but the fact that the property is frozen in the first place seems a bit strange as well. It doesn't seem like torii actually freezes anything and this might very well not be a problem in torii so feel free to close this and see this more as a notification that there's something strange going on.

**Comment by marcoow** [comment]
It turns out that Ember freezes concatenated properties after they were applied which is why the `requiredUrlParams` and `optionalUrlParams`. I'll submit a PR.

**Comment by Serabe** [comment]
I think this can be closed now. @marcoow?

**Comment by bantic** [comment]
Yep, this one should be closeable (via #341). Please reopen if I'm mistaken.

**Comment by bantic** [comment]
The fix is released in v0.8.2
