### ISSUE TITLE
doesn't work with safari private browsing

### ISSUE THREAD

**Issue by daegun** [Vestorly/torii#352]
since torii attempts to save to local storage in mixins/ui-service-mixin:46, it throws an error whenever you try to authenticate in safari:private-browsing

**Comment by alexmiddeleer** [comment]
We're also seeing this, I believe. We're logging the exception, "null is not an object (evaluating 'localStorage.setItem')".

**Comment by bantic** [comment]
@daegun Thanks for raising. This is a known issue (see https://github.com/Vestorly/torii/issues/265). Torii needs to be updated to fallback to a mechanism that's available in Safari Incognito (such as `postMessage`).
