### ISSUE TITLE
Firebase 3.x with Emberfire 2.x fails to authenticate

### ISSUE THREAD

**Issue by ksnyde** [Vestorly/torii#353]
I am upgrading an app that has used Emberfire 1.x (and using the Firebase 2.x API) to the latest and greatest. To my great disappointment, I can not authenticate using the Emberfire/Torii combination. The error I get is:

> TypeError: Cannot read property 'open' of undefined

And more explicitly, it appears this is the code sequence that is failing:

![2017-04-28_11-06-27](https://cloud.githubusercontent.com/assets/980757/25541639/3af69f5c-2c04-11e7-829d-96191db614d9.png)

The `provider` is set to 'firebase' and the `options` is set correctly with:

    {
      provider: 'password',
      email: email,
      password: password
    }

I had seen somewhere in the discussion of other issues that some people were having problems explicitly with `ember-source` **2.13.0** so I tried reverting to **2.12.2** where it had been working with emberfire 2.x API but the problem seems to be identical.

**Note:** this _may_ be a duplicate of the issue: https://github.com/Vestorly/torii/issues/350 but I wasn't completely sure

**Comment by ksnyde** [comment]
I can now verify that moving back to Ember 2.11.3 does bring this back to a working state. That is true for emberfire 2.x and 1.x (and the corresponding Firebase version).

**Comment by elgordino** [comment]
I had this problem. Updating to emberfire `2.0.7` fixed the issue. Using ember-source `2.13.0` and torii `0.8.2`.
