### ISSUE TITLE
stubValidSession doesn't work in ember-mocha

### ISSUE THREAD

**Issue by caseywatts** [Vestorly/torii#356]
When trying to migrate a test to ember-mocha's new setup style, I get this error:

```
TypeError: Cannot read property 'get' of undefined
```

I'm calling torii's `stubValidSession` defined here in a beforeEach, passing a valid `application` in.

It seems like torii expects `application.__container__.lookup('service:session')` to work. The function `application.__container__.lookup` is there, but it doesn't return anything from that call. It works for me with the old mocha setup format (startApp and destroyApp), but not with the new one `setupAcceptanceTest`. The new setupAcceptanceTest is just the normal one from `ember-test-helpers`: https://github.com/emberjs/ember-mocha/blob/master/lib/ember-mocha.js#L11 (from https://github.com/emberjs/ember-test-helpers)

I'm not sure if there's a better / more reliable way to do `application.__container__.lookup`?

Also see:
https://github.com/emberjs/ember-mocha/issues/151

**Comment by caseywatts** [comment]
This is the torii code for stubValidSession that does the lookup:
https://github.com/Vestorly/torii/blob/606334ca1832ecadc75628f8b6a2c4e110c1e642/test-support/helpers/torii.js#L2

**Comment by bantic** [comment]
Thanks for reporting. I haven't used ember-mocha much so I don't have a good guess as to what might be causing this. The fact that `application.__container__.lookup` stops returning something after changing to use the mocha `setupAcceptanceTest` makes me think that the problem lies on that side, but I'm going to spin up a test app with ember-mocha and Torii and see if I can reproduce this.

**Comment by bantic** [comment]
@caseywatts Hmm, it seemed to work ok for me. Here's the app I used:
https://github.com/bantic/__torii-mocha-example
The latest commit there is the relevant one: https://github.com/bantic/__torii-mocha-example/commit/a52c6e040e03b298b76d91b626de9148a7286f68

I'm going to close, but if I missed anything or if you have more info on a repro please reopen!
