### ISSUE TITLE
Torii service is undefined in Ember 2.13 inside of torii-session

### ISSUE THREAD

**Issue by crodriguez1a** [Vestorly/torii#358]
When running 2.13, it seems that the torii service is undefined? I'm not sure if some there is some compatibility issue with injecting the service via initializers?

https://github.com/Vestorly/torii/blob/master/addon/services/torii-session.js#L36

Injecting explicitly seems to solve the issue:
```es6

export default Ember.Service.extend(Ember._ProxyMixin, {
  torii: service(),

```

**Comment by crodriguez1a** [comment]
This actually may be an issue with Engines. Working on a clarification.

**Comment by Dhaulagiri** [comment]
@crodriguez1a can you confirm that you still experience this problem is you use torii 0.8.3 (released today)?

**Comment by crodriguez1a** [comment]
@Dhaulagiri Will do. I'll try the update first thing in the AM.

**Comment by crodriguez1a** [comment]
@Dhaulagiri https://github.com/Vestorly/torii/commit/67c09a9b4ff64e35fa58028e89ff49f18cf47d81 Fixed it. Mind publishing the 0.8.3 tag when you have a moment. Thanks again!

**Comment by crodriguez1a** [comment]
@Dhaulagiri Hey, btw thanks for getting to that so quickly man!

**Comment by Dhaulagiri** [comment]
@crodriguez1a should be published now
