### ISSUE TITLE
lookupAdapter not working so custom adapter not being added in container

### ISSUE THREAD

**Issue by vsymguysung** [Vestorly/torii#359]
After upgrading to `ember-cli 2.13.1`,  my custom adapter under `app/torii-adapter` is no longer be 
used via `lookupAdapter` function in `torii/addon/services/torii-session.js` because the `lookupAdapter` function returns a error.

**Comment by vsymguysung** [comment]
It seems my custom adapter is not being loaded in `Container` after upgrading to ember-cli `2.13.1`.  What file should I look at to find the codes that register custom adapters under `app/torii-adapter` folder ?

**Comment by vsymguysung** [comment]
I figured out the issue.  I was destructuring `Ember.Object` & `Ember.RSVP` in my custom torii adapter and it caused the error in `lookupAdapter` method after upgrading the ember-cli `2.13.1`.  Now I remove destructing `Ember.Object` & `Ember.RSVP`, it works well with ember-cli `2.13.1`.

**Comment by Dhaulagiri** [comment]
@vsymguysung sounds like you may have come across https://github.com/ember-cli/ember-cli/issues/7004

**Comment by vsymguysung** [comment]
@Dhaulagiri  Thanks for the information to clarify my issue. It helps.
