### ISSUE TITLE
Using "_lookupFactory" is deprecated. Please use container.factoryFor instead

### ISSUE THREAD

**Issue by oskarrough** [Vestorly/torii#362]
Hi, there's a new deprecation:

https://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor

It seems to come from here:

https://github.com/Vestorly/torii/blob/master/addon/lib/container-utils.js#L21

I tried setting up Torii to try and fix it but couldn't get it installed locally (windows pc atm).

**Comment by bantic** [comment]
@oskarrough Thanks for reporting. I'll fix this deprecation.
