### ISSUE TITLE
Can Torii be used without Ember-CLI or Ember App Kit?

### ISSUE THREAD

**Issue by xtrinsic** [Vestorly/torii#39]
I understand it can be used via Bower, but it is not explained clearly whether Torii can be used without either of the above utilities. (I am using Ember-Rails.)

**Comment by bantic** [comment]
Thanks for the notes and concern, here. In future versions of Torii we aren't going to continue to support non-ember-cli versions. But hopefully the code merged in #95 addresses your issue. Please feel free to add a comment if you are still on a non-ember-cli app that is using torii and I'd be happy to help you find a way to bridge this gap.
