### ISSUE TITLE
Passing options to torii open, fetch, & close not documented

### ISSUE THREAD

**Issue by davidlukerice** [Vestorly/torii#88]
Since [`proxyToProvider`](https://github.com/Vestorly/torii/blob/master/lib/torii/torii.js#L5) passes an `options` parameter to the provider's method, shouldn't it be documented for [`open`](https://github.com/Vestorly/torii/blob/master/lib/torii/torii.js#L55), [`fetch`](https://github.com/Vestorly/torii/blob/master/lib/torii/torii.js#L65), [`close`](https://github.com/Vestorly/torii/blob/master/lib/torii/torii.js#L76)? Or is passing options not intended?

Trying to see if [this](https://github.com/simplabs/ember-simple-auth/issues/295) ember-simple-auth extension is using torii correctly or not.

**Comment by fridaystreet** [comment]
I've been trying to see how this could actually work and I'm probably wrong, but I don't think there is anyway for the provider eg facebook-oauth2.js as it stands to use the options passed in. It looks like all the providers use import {configurable} from 'torii/configuration'; which appears to only ever be reading the ENV variables.

It's probably not the right way to go about it, but just by modifying the open function of the provider file to pass the options and set the parameters as per below seems to work fine.

//providers/facebook-oauth2.js
  
open: function(options) {

    for(key in options){
      this.set(key, options[key]);
    }
.......
